# Generated by Django 4.2.11 on 2026-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_add_step_transitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="form_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Form fields configuration for request type. Example: [{"name": "amount", "type": "number", "label": "Amount", "required": true}]',
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Enable/disable this request type"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Make this workflow available as a request type for users",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="request_name",
            field=models.CharField(
                blank=True,
                help_text='Display name for request type (e.g., "Expense Request")',
                max_length=255,
            ),
        ),
    ]
